### ISSUE TITLE
The website is not working

### ISSUE THREAD

**Issue by mkwsra** [peric/GetCountries#18]
Hey there, Thanks a lot for this useful tool.

but its, not working at all even the example link is not showing anything !

**Comment by peric** [comment]
Works on my machine :)

http://peric.github.io/GetCountries/

Don't know which browser you're using - I've tried it with latest Chrome and Firefox and it works.

**Comment by mkwsra** [comment]
My bad, JS file was blocked, I apologize it's working perfecrtly!
