### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by peric** [peric/GetCountries#2]
First thing...I want to thank you all for comments and visits.

Second thing...I'm wondering what will you like to add in existing "program"? I'm thinking about option to select between SQL, XML and maybe JSON code?

* if someone has already forked this Repo and started to work on that, I won't mind.

**Comment by toubou91** [comment]
Check out my <a href="https://github.com/peric/GetCountries/pull/19">pull request</a>!

![yaml_feature](https://cloud.githubusercontent.com/assets/5684688/7010168/e675c23a-dca7-11e4-894d-5bde0c098a4a.PNG)

![valid_yaml](https://cloud.githubusercontent.com/assets/5684688/7010171/ec284464-dca7-11e4-97f8-6117576f1884.PNG)

**Comment by peric** [comment]
Looks great. Is it too late if I merge it on Saturday or Sunday because I would like to test it before, and don't have access to my computer now (vacation time).

**Comment by toubou91** [comment]
Hello Drazen,

no problem, it's fine, enjoy your vacation!
Please let me know when you 're ready.

**Comment by peric** [comment]
Closed with #4.
