### ISSUE TITLE
Support timezones?

### ISSUE THREAD

**Issue by AmitMY** [peric/GetCountries#28]
What do you think of adding an option to also get the country's time codes, in a linked table (like the languages) or just the main timezone. From my experience, it should be in seconds, relative to GMT, meaning, for example Cyprus should be 3600, UK should be 0, etc...

**Comment by AmitMY** [comment]
Every language knows how to do this by setting the timezone, and especially for this need I just needed to use `moment`

**Comment by peric** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/QN2QgGzK/1-test)
