### ISSUE TITLE
website not working

### ISSUE THREAD

**Issue by raramuridesign** [peric/GetCountries#46]
http://peric.github.com/GetCountries
@peric Your site is not working

Seems this is the link
https://peric.github.io/GetCountries/

And you need to update this in your readme file

M.

**Comment by raramuridesign** [comment]
![image](https://user-images.githubusercontent.com/902376/153818750-42f18370-cd7f-45af-9876-675b96954149.png)

**Comment by peric** [comment]
Thanks for reporting this. Didn't know Github deprecated github.com for GitHub Pages.

Anyway, the new link is: https://peric.github.io/GetCountries/

I also updated the docs: https://github.com/peric/GetCountries/commit/a733bd26348aa7e7581a4fa4d8db74bdcba0a94d

**Comment by raramuridesign** [comment]
Excellent ;-)
